package ui;

import java.util.Observable;
import java.util.Observer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seongbo
 */
public class GameScreenPanel extends javax.swing.JPanel implements Observer
{
   
    /**
     * Creates new form gameScreen
     */
    public GameScreenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spriteOne = new javax.swing.JLabel();
        spriteTwo = new javax.swing.JLabel();
        usernameOneText = new javax.swing.JLabel();
        usernameTwoText = new javax.swing.JLabel();
        button_one_one = new javax.swing.JButton();
        button_one_two = new javax.swing.JButton();
        button_one_three = new javax.swing.JButton();
        button_one_four = new javax.swing.JButton();
        button_one_five = new javax.swing.JButton();
        button_one_six = new javax.swing.JButton();
        button_two_one = new javax.swing.JButton();
        button_two_two = new javax.swing.JButton();
        button_two_three = new javax.swing.JButton();
        button_two_four = new javax.swing.JButton();
        button_two_five = new javax.swing.JButton();
        button_two_six = new javax.swing.JButton();

        spriteOne.setText("Sprite1");

        spriteTwo.setText("Sprite2");

        usernameOneText.setText("username1");

        usernameTwoText.setText("username2");

        button_one_one.setText("poke1.1");

        button_one_two.setText("poke1.2");

        button_one_three.setText("poke1.3");

        button_one_four.setText("poke1.4");

        button_one_five.setText("poke1.5");

        button_one_six.setText("poke1.6");
        button_one_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_one_sixActionPerformed(evt);
            }
        });

        button_two_one.setText("poke2.1");

        button_two_two.setText("poke2.2");

        button_two_three.setText("poke2.3");

        button_two_four.setText("poke2.4");

        button_two_five.setText("poke2.5");

        button_two_six.setText("poke2.6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_two_one)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spriteTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameOneText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_one_one)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_one_two)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_one_three)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_one_four)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_one_five)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_one_six)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spriteOne, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_two_two)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_two_three)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_two_four)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_two_five)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_two_six)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                        .addComponent(usernameTwoText)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_two_one)
                    .addComponent(button_two_two)
                    .addComponent(button_two_three)
                    .addComponent(button_two_four)
                    .addComponent(button_two_five)
                    .addComponent(button_two_six)
                    .addComponent(usernameTwoText))
                .addGap(32, 32, 32)
                .addComponent(spriteTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(spriteOne, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_one_six)
                    .addComponent(button_one_five)
                    .addComponent(button_one_four)
                    .addComponent(button_one_three)
                    .addComponent(button_one_two)
                    .addComponent(button_one_one)
                    .addComponent(usernameOneText))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_one_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_one_sixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_one_sixActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_one_five;
    private javax.swing.JButton button_one_four;
    private javax.swing.JButton button_one_one;
    private javax.swing.JButton button_one_six;
    private javax.swing.JButton button_one_three;
    private javax.swing.JButton button_one_two;
    private javax.swing.JButton button_two_five;
    private javax.swing.JButton button_two_four;
    private javax.swing.JButton button_two_one;
    private javax.swing.JButton button_two_six;
    private javax.swing.JButton button_two_three;
    private javax.swing.JButton button_two_two;
    private javax.swing.JLabel spriteOne;
    private javax.swing.JLabel spriteTwo;
    private javax.swing.JLabel usernameOneText;
    private javax.swing.JLabel usernameTwoText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg)
    {
        
    }
}
