package ui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seongbo
 */
public class RequestBattlePanel extends javax.swing.JPanel {

    /**
     * Creates new form newJPanel
     */
    public RequestBattlePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        battleComputerButton = new javax.swing.JToggleButton();
        battleHumanButton = new javax.swing.JToggleButton();
        usernameText = new javax.swing.JLabel();
        winText = new javax.swing.JLabel();
        lossText = new javax.swing.JLabel();
        winCount = new javax.swing.JLabel();
        lossCount = new javax.swing.JLabel();

        battleComputerButton.setText("Battle Computer");

        battleHumanButton.setText("Battle Human");

        usernameText.setText("Username");

        winText.setText("Win:");

        lossText.setText("Loss:");

        winCount.setText("0");

        lossCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(battleHumanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(battleComputerButton)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(winText)
                        .addGap(18, 18, 18)
                        .addComponent(winCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(usernameText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lossText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lossCount, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winText)
                    .addComponent(winCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lossText)
                    .addComponent(lossCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(battleComputerButton)
                    .addComponent(battleHumanButton))
                .addGap(182, 182, 182))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton battleComputerButton;
    private javax.swing.JToggleButton battleHumanButton;
    private javax.swing.JLabel lossCount;
    private javax.swing.JLabel lossText;
    private javax.swing.JLabel usernameText;
    private javax.swing.JLabel winCount;
    private javax.swing.JLabel winText;
    // End of variables declaration//GEN-END:variables
}
