/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author seongbo
 */
public class TeamSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeamSelectionPanel
     */
    public TeamSelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamSelectionPanel = new javax.swing.JScrollPane();
        selectedTeamPanel = new javax.swing.JScrollPane();
        lockInButton = new javax.swing.JButton();
        pointsLeftText = new javax.swing.JLabel();
        pointsLeftCount = new javax.swing.JLabel();

        lockInButton.setText("Lock In");

        pointsLeftText.setText("Points Left:");

        pointsLeftCount.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamSelectionPanel)
            .addComponent(selectedTeamPanel)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lockInButton)
                .addGap(54, 54, 54)
                .addComponent(pointsLeftText)
                .addGap(18, 18, 18)
                .addComponent(pointsLeftCount)
                .addContainerGap(892, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(teamSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedTeamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lockInButton)
                    .addComponent(pointsLeftText)
                    .addComponent(pointsLeftCount))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lockInButton;
    private javax.swing.JLabel pointsLeftCount;
    private javax.swing.JLabel pointsLeftText;
    private javax.swing.JScrollPane selectedTeamPanel;
    private javax.swing.JScrollPane teamSelectionPanel;
    // End of variables declaration//GEN-END:variables
}
